### ISSUE TITLE
KeyError: 'migrate' on running poetry run flask db upgrade

### ISSUE THREAD

**Issue by mzch** [simple-login/app#1150]
Please note that this is only for bug report.

For help on your account, please reach out to us at hi[at]simplelogin.io. Please make sure to check out [our FAQ](https://simplelogin.io/faq/) that contains  frequently asked questions.

For feature request, you can use our [forum](https://github.com/simple-login/app/discussions/categories/feature-request).

For self-hosted question/issue, please ask in [self-hosted forum](https://github.com/simple-login/app/discussions/categories/self-hosting-question)

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
DB migration aborts. When applying the following patch, DB migrate finisshed successfully.

```diff
--- server.py	2022-07-07 14:22:34.663919666 -0700
+++ ../app/server.py	2022-07-05 02:48:28.623289847 -0700
@@ -27,6 +27,9 @@
 from sentry_sdk.integrations.sqlalchemy import SqlalchemyIntegration
 from werkzeug.middleware.proxy_fix import ProxyFix

+from flask_sqlalchemy import SQLAlchemy
+from flask_migrate import Migrate
+
 from app import paddle_utils, config
 from app.admin_model import (
     SLAdminIndexView,
@@ -140,6 +143,8 @@
     app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
     # enable to print all queries generated by sqlalchemy
     # app.config["SQLALCHEMY_ECHO"] = True
+    db = SQLAlchemy(app)
+    migrate = Migrate(app, db)

     app.secret_key = FLASK_SECRET
```

**Expected behavior**
DB migration finished successfully without patching `server.py`.

**Additional context**
- Log
```
simplelogin@n16:~/app-test$ poetry run flask db upgrade
Skipping virtualenv creation, as specified in config file.
>>> URL: https://exch.email
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
Paddle param not set
Upload files to local dir
>>> init logging <<<
2022-07-07 21:25:41,166 - SL - DEBUG - 150821 - "/srv/simplelogin/app-test/app/utils.py:14" - <module>() -  - load words file: /srv/simplelogin/app-test/local_data/words.txt
Traceback (most recent call last):
  File "/srv/simplelogin/.pyenv/versions/3.7.13/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/srv/simplelogin/.pyenv/versions/3.7.13/lib/python3.7/site-packages/flask_migrate/__init__.py", line 269, in upgrade
    config = current_app.extensions['migrate'].migrate.get_config(directory,
KeyError: 'migrate'
```

**Comment by mzch** [comment]
Sorry, I forgot closing this ticket. Yes, it's OK. Thanks!
