### ISSUE TITLE
No such file or directory: '/code/dkim.key' during database migration

### ISSUE THREAD

**Issue by DANgerous25** [simple-login/app#1181]
### Discussed in https://github.com/simple-login/app/discussions/1180

<div type='discussions-op-text'>

<sup>Originally posted by **DANgerous25** July 22, 2022</sup>
Hi, I’m at the “database migration” stage of the self-host setup. When I try to execute I get the error that /code/dkim.key is not found. My dkim.key file is in the ~/sl directory. Please can someone help me to fix this error, I’m sure it’s something really stupid! Thank you.

`simple@myhost:~/sl$ docker run --rm     --name sl-migration     -v $(pwd)/sl:/sl     -v $(pwd)/sl/upload:/code/static/upload     -v $(pwd)/dkim.key:/dkim.key     -v $(pwd)/dkim.pub.key:/dkim.pub.key     -v $(pwd)/simplelogin.env:/code/.env     --network="sl-network"     simplelogin/app:3.4.0 flask db upgrade`
>>> URL: http://app.mydomain.whatever
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/wsgi.py", line 1, in <module>
    from server import create_app
  File "/code/server.py", line 28, in <module>
    from app import paddle_utils, s3, config
  File "/code/app/paddle_utils.py", line 18, in <module>
    from app.config import PADDLE_PUBLIC_KEY_PATH, PADDLE_VENDOR_ID, PADDLE_AUTH_CODE
  File "/code/app/config.py", line 156, in <module>
    with open(DKIM_PRIVATE_KEY_PATH) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/code/dkim.key'

</div>

**Comment by DANgerous25** [comment]
Error was a typo in the simplelogin.env file. Sorry for anyone that wasted time on this (although it did stump me for many, many hours!)
