### ISSUE TITLE
Not receiving the mails: dkim.KeyFormatError: Unparsable private key: Unexpected tag (got 30, expecting 02)

### ISSUE THREAD

**Issue by akash07k** [simple-login/app#1203]
Please note that this is only for bug report.

For help on your account, please reach out to us at hi[at]simplelogin.io. Please make sure to check out [our FAQ](https://simplelogin.io/faq/) that contains  frequently asked questions.

For feature request, you can use our [forum](https://github.com/simple-login/app/discussions/categories/feature-request).

For self-hosted question/issue, please ask in [self-hosted forum](https://github.com/simple-login/app/discussions/categories/self-hosting-question)

## Prerequisites
 [ ] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

Not receiving the emails from simplelogin instance.

**Describe the bug**

I'm hosting the simplelogin instance on my server and building the image it from source.\
Everything is fine, but whenever I'm creating an account, I'm not getting any mail on my mail address.
Following are the logs on my sl-app container:

```
2022-07-29 19:08:15,904 - SL - WARNING - 9 - "/code/app/email_utils.py:461" - add_dkim_signature() -  - DKIM fail with [b'Message-ID', b'Date', b'Subject', b'From', b'To']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 140, in parse_private_key
    pka = asn1_parse(ASN1_RSAPrivateKey, data)
  File "/usr/local/lib/python3.7/site-packages/dkim/asn1.py", line 85, in asn1_parse
    r.append(asn1_parse(t[1], data[i:i+length]))
  File "/usr/local/lib/python3.7/site-packages/dkim/asn1.py", line 92, in asn1_parse
    "Unexpected tag (got %02x, expecting %02x)" % (tag, t[0]))
dkim.asn1.ASN1FormatError: Unexpected tag (got 30, expecting 02)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 827, in sign
    pk = parse_pem_private_key(privkey)
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 170, in parse_pem_private_key
    return parse_private_key(pkdata)
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 142, in parse_private_key
    raise UnparsableKeyError('Unparsable private key: ' + str(e))
dkim.crypto.UnparsableKeyError: Unparsable private key: Unexpected tag (got 30, expecting 02)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/app/email_utils.py", line 458, in add_dkim_signature
    add_dkim_signature_with_header(msg, email_domain, dkim_headers)
  File "/code/app/email_utils.py", line 489, in add_dkim_signature_with_header
    include_headers=dkim_headers,
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 1335, in sign
    return d.sign(selector, domain, privkey, identity=identity, canonicalize=canonicalize, include_headers=include_headers, length=length)
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 829, in sign
    raise KeyFormatError(str(e))
dkim.KeyFormatError: Unparsable private key: Unexpected tag (got 30, expecting 02)
2022-07-29 19:08:15,907 - SL - WARNING - 9 - "/code/app/email_utils.py:461" - add_dkim_signature() -  - DKIM fail with [b'From', b'To']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 140, in parse_private_key
    pka = asn1_parse(ASN1_RSAPrivateKey, data)
  File "/usr/local/lib/python3.7/site-packages/dkim/asn1.py", line 85, in asn1_parse
    r.append(asn1_parse(t[1], data[i:i+length]))
  File "/usr/local/lib/python3.7/site-packages/dkim/asn1.py", line 92, in asn1_parse
    "Unexpected tag (got %02x, expecting %02x)" % (tag, t[0]))
dkim.asn1.ASN1FormatError: Unexpected tag (got 30, expecting 02)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 827, in sign
    pk = parse_pem_private_key(privkey)
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 170, in parse_pem_private_key
    return parse_private_key(pkdata)
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 142, in parse_private_key
    raise UnparsableKeyError('Unparsable private key: ' + str(e))
dkim.crypto.UnparsableKeyError: Unparsable private key: Unexpected tag (got 30, expecting 02)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/app/email_utils.py", line 458, in add_dkim_signature
    add_dkim_signature_with_header(msg, email_domain, dkim_headers)
  File "/code/app/email_utils.py", line 489, in add_dkim_signature_with_header
    include_headers=dkim_headers,
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 1335, in sign
    return d.sign(selector, domain, privkey, identity=identity, canonicalize=canonicalize, include_headers=include_headers, length=length)
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 829, in sign
    raise KeyFormatError(str(e))
dkim.KeyFormatError: Unparsable private key: Unexpected tag (got 30, expecting 02)
2022-07-29 19:08:15,909 - SL - WARNING - 9 - "/code/app/email_utils.py:461" - add_dkim_signature() -  - DKIM fail with [b'Message-ID', b'Date']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 140, in parse_private_key
    pka = asn1_parse(ASN1_RSAPrivateKey, data)
  File "/usr/local/lib/python3.7/site-packages/dkim/asn1.py", line 85, in asn1_parse
    r.append(asn1_parse(t[1], data[i:i+length]))
  File "/usr/local/lib/python3.7/site-packages/dkim/asn1.py", line 92, in asn1_parse
    "Unexpected tag (got %02x, expecting %02x)" % (tag, t[0]))
dkim.asn1.ASN1FormatError: Unexpected tag (got 30, expecting 02)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 827, in sign
    pk = parse_pem_private_key(privkey)
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 170, in parse_pem_private_key
    return parse_private_key(pkdata)
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 142, in parse_private_key
    raise UnparsableKeyError('Unparsable private key: ' + str(e))
dkim.crypto.UnparsableKeyError: Unparsable private key: Unexpected tag (got 30, expecting 02)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/app/email_utils.py", line 458, in add_dkim_signature
    add_dkim_signature_with_header(msg, email_domain, dkim_headers)
  File "/code/app/email_utils.py", line 489, in add_dkim_signature_with_header
    include_headers=dkim_headers,
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 1335, in sign
    return d.sign(selector, domain, privkey, identity=identity, canonicalize=canonicalize, include_headers=include_headers, length=length)
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 829, in sign
    raise KeyFormatError(str(e))
dkim.KeyFormatError: Unparsable private key: Unexpected tag (got 30, expecting 02)
2022-07-29 19:08:15,911 - SL - WARNING - 9 - "/code/app/email_utils.py:461" - add_dkim_signature() -  - DKIM fail with [b'From']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 140, in parse_private_key
    pka = asn1_parse(ASN1_RSAPrivateKey, data)
  File "/usr/local/lib/python3.7/site-packages/dkim/asn1.py", line 85, in asn1_parse
    r.append(asn1_parse(t[1], data[i:i+length]))
  File "/usr/local/lib/python3.7/site-packages/dkim/asn1.py", line 92, in asn1_parse
    "Unexpected tag (got %02x, expecting %02x)" % (tag, t[0]))
dkim.asn1.ASN1FormatError: Unexpected tag (got 30, expecting 02)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 827, in sign
    pk = parse_pem_private_key(privkey)
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 170, in parse_pem_private_key
    return parse_private_key(pkdata)
  File "/usr/local/lib/python3.7/site-packages/dkim/crypto.py", line 142, in parse_private_key
    raise UnparsableKeyError('Unparsable private key: ' + str(e))
dkim.crypto.UnparsableKeyError: Unparsable private key: Unexpected tag (got 30, expecting 02)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/app/email_utils.py", line 458, in add_dkim_signature
    add_dkim_signature_with_header(msg, email_domain, dkim_headers)
  File "/code/app/email_utils.py", line 489, in add_dkim_signature_with_header
    include_headers=dkim_headers,
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 1335, in sign
    return d.sign(selector, domain, privkey, identity=identity, canonicalize=canonicalize, include_headers=include_headers, length=length)
  File "/usr/local/lib/python3.7/site-packages/dkim/__init__.py", line 829, in sign
    raise KeyFormatError(str(e))
dkim.KeyFormatError: Unparsable private key: Unexpected tag (got 30, expecting 02)
2022-07-29 19:08:15,911 - SL - ERROR - 9 - "/code/server.py:380" - error_handler() -  - Cannot create DKIM signature
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_limiter/extension.py", line 702, in __inner
    return obj(*a, **k)
  File "/code/app/auth/views/forgot_password.py", line 37, in forgot_password
    send_reset_password_email(user)
  File "/code/app/dashboard/views/setting.py", line 433, in send_reset_password_email
    email_utils.send_reset_password_email(user.email, reset_password_link)
  File "/code/app/email_utils.py", line 163, in send_reset_password_email
    reset_password_link=reset_password_link,
  File "/code/app/email_utils.py", line 333, in send_email
    add_dkim_signature(msg, email_domain)
  File "/code/app/email_utils.py", line 473, in add_dkim_signature
    raise Exception("Cannot create DKIM signature")
Exception: Cannot create DKIM signature
2022-07-29 19:08:15,914 - SL - DEBUG - 9 - "/code/server.py:283" - after_request() -  - 10.0.0.1 POST /auth/forgot_password ImmutableMultiDict([]) 500, takes 0.03918600082397461
2022-07-29 23:59:39,513 - SL - DEBUG - 10 - "/code/server.py:283" - after_request() -  - 10.0.0.1 GET / ImmutableMultiDict([]) 302, takes 0.00030994415283203125
2022-07-29 23:59:39,610 - SL - DEBUG - 9 - "/code/server.py:283" - after_request() -  - 10.0.0.1 GET /auth/login ImmutableMultiDict([]) 200, takes 0.001558065414428711
2022-07-30 07:42:07,346 - SL - DEBUG - 9 - "/code/server.py:283" - after_request() -  - 198.235.24.11 GET / ImmutableMultiDict([]) 302, takes 0.00031948089599609375
2022-07-30 07:42:07,858 - SL - DEBUG - 10 - "/code/server.py:283" - after_request() -  - 10.0.0.1 GET /auth/login ImmutableMultiDict([]) 200, takes 0.006139278411865234
```
**Expected behavior**
Mails should be received without any error.
**Screenshots**

**Environment (If applicable):**
 - OS: Linux, Mac, Windows
 - Browser: Firefox, Chrome, Brave, Safari
 - Version [e.g. 78]

**Additional context**

**Comment by akash07k** [comment]
@Spitfireap  Wow, that's wonderful to know.
so, till when this fix land in SimpleLogin images?
And can I replace my DKIM keys without setting up the whole instance from the scratch?
> [Upstream bug](https://bugs.launchpad.net/dkimpy/+bug/1978835) has been fixed. It will be available in the next release of dkimpy. In the meantime, either use openssl1 or use `-traditional` argument for private key generation :)

**Comment by Spitfireap** [comment]
Not before the fix is released on dkimpy, I have no timeline, but it should be rather quick. 
To replace your DKIM key you just need to replace the one you already have (don't forget to update your dns!) and restart all the docker containers (a reboot of the vps can work also).

**Comment by akash07k** [comment]
Wonderful.

I'll try it.

Thanks a lot.

Also, I see that SimpleLogin 4.12.0 is just released. any idea that it 
can be used stabally or not?

**Comment by Spitfireap** [comment]
No clue. Perhaps @nguyenkims knows more about it. 

But you have to understand that most development you see here is for the commercial side of SimpleLogin and not self host environment. SimpleLogin as self hosted environment doesn't require that much more it already has. So 4.6.2 is good enough I think :)

**Comment by akash07k** [comment]
@Spitfireap 
Ah, I got it.
I'll continue with 4.6 then

**Comment by nguyenkims** [comment]
@akash07k @Spitfireap The 4.12.0 is actually our internal version and hasn't been tested for self hosting. It usually has a lot of commercial features related to subscriptions that aren't needed for self hosting.

**Comment by akash07k** [comment]
@nguyenkims  Any plans to make the latest builds ready for selfhosting?

**Comment by MuhammadNaeem42** [comment]
i will help you to setup this application 
contact me https://www.fiverr.com/s/9W3PNA
![simple](https://github.com/simple-login/app/assets/106573678/25e18c92-e0a9-4764-8a58-1592b2ae6283)

**Comment by SwapnilSoni1999** [comment]
Still facing the same issue in latest version
