### ISSUE TITLE
Server Error sending activation email

### ISSUE THREAD

**Issue by StuartHaire** [simple-login/app#1289]
I've setup everything as per the instructions and I'm receiving the following error when I try to resend the activation email. Not sure the issue.

```
2022-09-16 13:36:35,088 - SL - DEBUG - "/code/app/auth/views/resend_activation.py:32" - resend_activation() -  - user <User 3  MYEMAIL@gmail.com> is not activated
2022-09-16 13:36:35,124 - SL - DEBUG - "/code/app/email_utils.py:250" - send_email() -  - send email to MYEMAIL@gmail.com, subject Just one more step to join SimpleLogin
2022-09-16 13:36:35,157 - SL - ERROR - "/code/server.py:541" - error_handler() -  - {'MYEMAIL@gmail.com': (451, b'4.3.0 <MYEMAIL@gmail.com>: Temporary lookup failure')}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/code/app/auth/views/resend_activation.py", line 37, in resend_activation
    send_activation_email(user, request.args.get("next"))
  File "/code/app/auth/views/register.py", line 113, in send_activation_email
    email_utils.send_activation_email(user.email, activation_link)
  File "/code/app/email_utils.py", line 121, in send_activation_email
    email=email,
  File "/code/app/email_utils.py", line 294, in send_email
    smtp.sendmail(TRANSACTIONAL_BOUNCE_EMAIL.format(transaction.id), to_email, msg_raw)
  File "/usr/local/lib/python3.7/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'MYEMAIL@gmail.com': (451, b'4.3.0 <MYEMAIL@gmail.com>: Temporary lookup failure')}
2022-09-16 13:36:35,160 - SL - DEBUG - "/code/server.py:444" - after_request() -  - 82.1.225.86 POST /auth/resend_activation ImmutableMultiDict([]) 500
```

**Comment by nguyenkims** [comment]
@StuartHaire I'd recommend to go through the troubleshooting guide https://github.com/simple-login/app/blob/master/docs/troubleshooting.md that might help detect the issue.

**Comment by StuartHaire** [comment]
@nguyenkims it was infact a configuration issue on my end. I've got it working now, however when I test my email I get dkim not valid. https://www.mail-tester.com/test-dnbmdviax
