### ISSUE TITLE
Error when performing db migration step on setup

### ISSUE THREAD

**Issue by DANgerous25** [simple-login/app#1292]
Hi, I'm having the same issue as [this one](https://github.com/simple-login/app/issues/326), however the OP closed it without a solution. I also found another similar one where the OP had changed the default paths, but I don't think I've changed my default paths.

I am working through the standard setup steps as per the readme. I have got as far as the db migration step, running the command below:

```
sudo docker run --rm \
    --name sl-migration \
    -v /home/simple/sl/sl:/sl \
    -v /home/simple/sl/sl/upload:/code/static/upload \
    -v /home/simple/sl/dkim.key:/dkim.key \
    -v /home/simple/sl/dkim.pub.key:/dkim.pub.key \
    -v /home/simple/sl/simplelogin.env:/code/.env \
    --network="sl-network" \
    simplelogin/app:3.4.0 flask db upgrade
```

Eventually I get this error trace:

```
Digest: sha256:e947713b20bf37e148ebb3a6dedd130b25073d12947c4d641dd00848dd531da3
Status: Downloaded newer image for simplelogin/app:3.4.0
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/wsgi.py", line 1, in <module>
    from server import create_app
  File "/code/server.py", line 28, in <module>
    from app import paddle_utils, s3, config
  File "/code/app/paddle_utils.py", line 18, in <module>
    from app.config import PADDLE_PUBLIC_KEY_PATH, PADDLE_VENDOR_ID, PADDLE_AUTH_CODE
  File "/code/app/config.py", line 55, in <module>
    URL = os.environ["URL"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'URL'
```

Here's my simplelogin.env (key elements redacted):

```
# WebApp URL
URL=https://xyz.xyz.xyz

# domain used to create alias
EMAIL_DOMAIN=xyz.xyz

# transactional email is sent from this email address
SUPPORT_EMAIL=support@xyz.xyz

# custom domain needs to point to these MX servers
EMAIL_SERVERS_WITH_PRIORITY=[(10, "xyz.xyz.xyz.")]

# By default, new aliases must end with ".{random_word}". This is to avoid a person taking all "nice" aliases.
# this option doesn't make sense in self-hosted. Set this variable to disable this option.
DISABLE_ALIAS_SUFFIX=1

# the DKIM private key used to compute DKIM-Signature
DKIM_PRIVATE_KEY_PATH=/dkim.key

# DB Connection
DB_URI=postgresql://my_db_user:my_db_password@sl-db:5432/simplelogin

FLASK_SECRET=what_is_a_flask_anyway

GNUPGHOME=/sl/pgp

LOCAL_FILE_UPLOAD=1

POSTFIX_SERVER=10.0.0.1

```
Any ideas? I'm running this on Fedora Server 36. I had previously installed this on Ubuntu 20x LTS with pretty much the same config and it worked. So I'm stumped!

Thanks for your help!

**Comment by DANgerous25** [comment]
p.s. I found in the thread about the beta release that "flask db upgrade" -> "alembic upgrade head". I get a similar problem:

```
sudo docker run --rm \
    --name sl-migration \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/sl/upload:/code/static/upload \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -v $(pwd)/simplelogin.env:/code/.env \
    --network="sl-network" \
    simplelogin/app:4.6.2-beta alembic upgrade head
Unable to find image 'simplelogin/app:4.6.2-beta' locally
4.6.2-beta: Pulling from simplelogin/app
d836772a1c1f: Pull complete
66a9e63c657a: Pull complete
d1989b6e74cf: Pull complete
c28818711e1e: Pull complete
5084fa7ebd74: Pull complete
7f162c881e4f: Pull complete
fa5c3534431d: Pull complete
30596f5e8e78: Pull complete
4861fe1f6551: Pull complete
149501c651fb: Pull complete
eb8fe0958140: Pull complete
04def6219750: Pull complete
df0aa816c0f5: Pull complete
044c9dca73bd: Pull complete
Digest: sha256:67f4b35dd35c4a26c21880034e8731a828bae6ca93d8c5e7f0c595e68fb2b51d
Status: Downloaded newer image for simplelogin/app:4.6.2-beta
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url_list' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'delim' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'url' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url_list' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'delim' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'url' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'angle_addr' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'name_addr' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'phrase' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url_list' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'delim' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'addr_spec' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'angle_addr' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'name_addr' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'phrase' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'local_part' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'domain' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'quoted_string' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'domain_literal' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'quoted_string_text' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'domain_literal_text' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url_list' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'delim' is unreachable
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 555, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 26, in <module>
    from app.models import Base
  File "/code/app/models.py", line 29, in <module>
    from app import s3
  File "/code/app/s3.py", line 8, in <module>
    from app.config import (
  File "/code/app/config.py", line 53, in <module>
    URL = os.environ["URL"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'URL'
```

**Comment by DANgerous25** [comment]
I tried a complete re-install and still no joy. So I tried on ubuntu instead (using beta version) and didn't have this problem. So I think it is something to do with Fedora or how I've installed it on Fedora. Either way, doesn't matter now because I don't have Fedora any longer!

**Comment by nguyenkims** [comment]
@DANgerous25 the error says that the `URL` setting isn't set. I wonder if you can check if the setting file `$(pwd)/simplelogin.env` is correct?

**Comment by DANgerous25** [comment]
> @DANgerous25 the error says that the `URL` setting isn't set. I wonder if you can check if the setting file `$(pwd)/simplelogin.env` is correct?

Hi, thank you for taking the time to reply. As you can see from my original post the setting is present in the file.

Unfortunately I gave up trying to fix this, and re-installed the OS to use Ubuntu instead of Fedora. I had very few problems with the Ubuntu install compared to Fedora.

Hence we can close / won’t fix this as I have no way to test any further suggestions.

**Comment by bugoverfl0w** [comment]
I have the same error here.

What is the solution?

**Comment by DANgerous25** [comment]
> I have the same error here.
> 
> What is the solution?

I never found the issue, and I only had it with Fedora. Ubuntu no problem. Clean install on both, same configs etc., just doesn't work on Fedora.

If your issue is on Ubuntu then unfortunately I can't help!

**Comment by felixyates** [comment]
I'm trying it on Ubuntu and no luck >_<

**Comment by DANgerous25** [comment]
> I'm trying it on Ubuntu and no luck >_<

Are you using the beta version? If yes and on clean install of Ubuntu it really should work.

**Comment by felixyates** [comment]
> > I'm trying it on Ubuntu and no luck >_<
> 
> 
> 
> Are you using the beta version? If yes and on clean install of Ubuntu it really should work. 

Please could you link the version that worked for you? I'm useless at finding specific versions on GitHub 😅

**Comment by DANgerous25** [comment]
> > > I'm trying it on Ubuntu and no luck >_<
> > 
> > 
> > Are you using the beta version? If yes and on clean install of Ubuntu it really should work.
> 
> Please could you link the version that worked for you? I'm useless at finding specific versions on GitHub 😅

Ok, don't laugh at my scripting abilities as I am not an expert, but I cobbled this together which works for me. It's a half-finished script but it does the job for me, and I use it to occasionally restart SL (probably overkill for this purpose). Make sure you substitute your own values for the database username and password. Put this script in your sl directory and try running it.

Change these below (and anything else that you changed from the install guide, which hopefully you didn't):

POSTGRES_PASSWORD=your_password 
POSTGRES_USER=your_db_user

```
#!/bin/bash

TS=`date +"%Y%m%d%H%M%S"`
echo '=============================='
echo '| SimpleLogin Restart Script |'
echo '| v1.0 20220927 DANgerous25  |'
echo '=============================='
echo

if [[ ${1} == "--debug" ]]; then DEBUG=1 ; fi
if [[ ${1} == "--stop" ]]; then STOP=1 ; fi
LOG_PATH="${PWD}/logs/restart_sl.log.$TS"
touch ${LOG_PATH}

function suppress
{
   /bin/rm --force /tmp/suppress.out 2> /dev/null; \
   ${1+"$@"} > /tmp/suppress.out 2>&1 || \
   cat /tmp/suppress.out; \
   /bin/rm /tmp/suppress.out;
}

function log
{
    LOG_TYPE=${1}
    LOG_STR=${2}
    LOG_TS=`date +"%Y%m%d%H%M%S"`
    echo "[ ${LOG_TYPE} ] | ${LOG_TS} | ${LOG_STR}" >> ${LOG_PATH}
}

echo Stop services if running...

CMD="suppress sudo systemctl stop postgresql"
DESC="Stop postgresql"
OUT=$(${CMD} 2>&1)
log "INFO." "Description = ${DESC}"
log "INFO." "Command = ${CMD}"
log "INFO." "Output ="
log "OUT.." "${OUT}"
#cat ${LOG_PATH} ${OUT} > ${LOG_PATH}

suppress sudo systemctl stop postfix

echo Removing containers...

#sudo docker rm -fv $(sudo docker ps -aq)
# Above line deprecated as it kills containers from other apps!

# Pull the latest version
suppress sudo docker pull simplelogin/app:4.6.5-beta

# Stop SimpleLogin containers
suppress sudo docker stop sl-email sl-migration sl-app sl-db sl-job-runner

# Make sure to remove these containers to avoid conflict
suppress sudo docker rm -f sl-email sl-migration sl-app sl-db sl-job-runner
suppress sudo docker network rm sl-network

# Quit if just stopping

if [[ $STOP -eq 1 ]] 
    then
    echo Stopped everything, exiting. Goodbye!
    exit 0
fi

echo 'Refreshing container (if necessary)'

suppress sudo docker pull simplelogin/app:4.6.5-beta

echo Preparing network...

suppress sudo docker network create -d bridge \
    --subnet=10.0.0.0/24 \
    --gateway=10.0.0.1 \
    sl-network

echo Setting up database...

suppress docker run -d \
    --name sl-db \
    -e POSTGRES_PASSWORD=your_password \
    -e POSTGRES_USER=your_db_user \
    -e POSTGRES_DB=simplelogin \
    -p 127.0.0.1:5432:5432 \
    -v $(pwd)/sl/db:/var/lib/postgresql/data \
    --restart always \
    --network="sl-network" \
    postgres:12.1

echo Running DB migration...

suppress docker run --rm \
    --name sl-migration \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/sl/upload:/code/static/upload \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -v $(pwd)/simplelogin.env:/code/.env \
    --network="sl-network" \
    simplelogin/app:4.6.5-beta alembic upgrade head

echo Initialising data...

suppress docker run --rm \
    --name sl-init \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/simplelogin.env:/code/.env \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    --network="sl-network" \
    simplelogin/app:4.6.5-beta python init_app.py

echo Starting web app...

suppress docker run -d \
    --name sl-app \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/sl/upload:/code/static/upload \
    -v $(pwd)/simplelogin.env:/code/.env \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -p 127.0.0.1:7777:7777 \
    --restart always \
    --network="sl-network" \
    simplelogin/app:4.6.5-beta

echo Starting email handler...

suppress docker run -d \
    --name sl-email \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/sl/upload:/code/static/upload \
    -v $(pwd)/simplelogin.env:/code/.env \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -p 127.0.0.1:20381:20381 \
    --restart always \
    --network="sl-network" \
    simplelogin/app:4.6.5-beta python email_handler.py

echo Starting job runner...

#sudo docker run -d     --name sl-job-runner     -v $(pwd)/sl:/sl     -v $(pwd)/sl/upload:/code/static/upload     -v $(pwd)/simplelogin.env:/code/.env     -v $(pwd)/dkim.key:/dkim.key     -v $(pwd)/dkim.pub.key:/dkim.pub.key     --restart always     --network="sl-network"     simplelogin/app:4.6.5-beta python job_runner.py

suppress docker run -d \
    --name sl-job-runner \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/sl/upload:/code/static/upload \
    -v $(pwd)/simplelogin.env:/code/.env \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    --restart always \
    --network="sl-network" \
    simplelogin/app:4.6.5-beta python job_runner.py


echo Restarting postfix...

suppress sudo systemctl restart postfix

echo All done!
```

Let me know if this works!
