### ISSUE TITLE
HIBP

### ISSUE THREAD

**Issue by DNCD** [simple-login/app#1322]
### Discussed in https://github.com/simple-login/app/discussions/1290

<div type='discussions-op-text'>

<sup>Originally posted by **DNCD** September 16, 2022</sup>
Hi,

Everything is running great except when I try to enable HIBP on simplelogin.env. I have added the following code to the env file. I did purchase an API key from HIBP 

`HIBP_SCAN_INTERVAL_DAYS = 7
HIBP_API_KEYS=[REDACTED]`

I get 502 Bad Gateway and the following error. 

`
[2022-09-16 15:46:05 +0000] [8] [INFO] Worker exiting (pid: 8)
>>> URL: https://app.example.com
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
Paddle param not set
Upload files to local dir
[2022-09-16 15:46:05 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/wsgi.py", line 1, in <module>
    from server import create_app
  File "/code/server.py", line 32, in <module>
    from app import paddle_utils, config
  File "/code/app/paddle_utils.py", line 18, in <module>
    from app.config import PADDLE_PUBLIC_KEY_PATH, PADDLE_VENDOR_ID, PADDLE_AUTH_CODE
  File "/code/app/config.py", line 418, in <module>
    HIBP_API_KEYS = sl_getenv("HIBP_API_KEYS", list) or []
  File "/code/app/config.py", line 36, in sl_getenv
    return literal_eval(value)
  File "/usr/local/lib/python3.10/ast.py", line 108, in literal_eval
    return _convert(node_or_string)
  File "/usr/local/lib/python3.10/ast.py", line 88, in _convert
    return list(map(_convert, node.elts))
  File "/usr/local/lib/python3.10/ast.py", line 107, in _convert
    return _convert_signed_num(node)
  File "/usr/local/lib/python3.10/ast.py", line 81, in _convert_signed_num
    return _convert_num(node)
  File "/usr/local/lib/python3.10/ast.py", line 72, in _convert_num
    _raise_malformed_node(node)
  File "/usr/local/lib/python3.10/ast.py", line 69, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string on line 1: <ast.Name object at 0x7fc3eb1646a0>
[2022-09-16 15:46:05 +0000] [9] [INFO] Worker exiting (pid: 9)
[2022-09-16 15:46:05 +0000] [1] [INFO] Shutting down: Master
[2022-09-16 15:46:05 +0000] [1] [INFO] Reason: Worker failed to boot.
[2022-09-16 15:46:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2022-09-16 15:46:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:7777 (1)
[2022-09-16 15:46:08 +0000] [1] [INFO] Using worker: sync
[2022-09-16 15:46:08 +0000] [7] [INFO] Booting worker with pid: 7
[2022-09-16 15:46:08 +0000] [8] [INFO] Booting worker with pid: 8

`

</div>

**Comment by nguyenkims** [comment]
The HIBP check can be run by running `python /code/cron.py -j check_hibp` inside the container. Our latest version for self hosting is https://github.com/simple-login/app/tree/4.6.2-beta
