### ISSUE TITLE
Error upgrading 2.1.0 to 2.1.2

### ISSUE THREAD

**Issue by nkaplatt** [simple-login/app#133]
I've started the process of upgrading to version 3.0.1, as I was previously running version 2.0.0 I planned to do it in the outlined steps.

First off I upgraded to 2.1.0 without issue, but it in the process of upgrading to 2.1.2 I've encountered this issue when hitting the dashboard.

```
2020-04-21 17:24:29,211 - sl - ERROR - 9 - server:296 - error_handler - (psycopg2.errors.UndefinedTable) relation "alias" does not exist
LINE 2: FROM client_user LEFT OUTER JOIN alias AS alias_1 ON alias_1...
                                         ^

[SQL: SELECT client_user.id AS client_user_id, client_user.created_at AS client_user_created_at, client_user.updated_at AS client_user_updated_at, client_user.user_id AS client_user_user_id, client_user.client_id AS client_user_client_id, client_user.alias_id AS client_user_alias_id, client_user.name AS client_user_name, client_user.default_avatar AS client_user_default_avatar, alias_1.id AS alias_1_id, alias_1.created_at AS alias_1_created_at, alias_1.updated_at AS alias_1_updated_at, alias_1.user_id AS alias_1_user_id, alias_1.email AS alias_1_email, alias_1.enabled AS alias_1_enabled, alias_1.custom_domain_id AS alias_1_custom_domain_id, alias_1.automatic_creation AS alias_1_automatic_creation, alias_1.directory_id AS alias_1_directory_id, alias_1.note AS alias_1_note, alias_1.mailbox_id AS alias_1_mailbox_id, client_1.id AS client_1_id, client_1.created_at AS client_1_created_at, client_1.updated_at AS client_1_updated_at, client_1.oauth_client_id AS client_1_oauth_client_id, client_1.oauth_client_secret AS client_1_oauth_client_secret, client_1.name AS client_1_name, client_1.home_url AS client_1_home_url, client_1.published AS client_1_published, client_1.user_id AS client_1_user_id, client_1.icon_id AS client_1_icon_id
FROM client_user LEFT OUTER JOIN alias AS alias_1 ON alias_1.id = client_user.alias_id LEFT OUTER JOIN client AS client_1 ON client_1.id = client_user.client_id
WHERE client_user.user_id = %(user_id_1)s]
[parameters: {'user_id_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "alias" does not exist
```

I had a quick dig around in the codebase but come up short, I was under the impression the database only had changes between v2 to v3 but seemingly I've possibly done something wrong. Thanks!

**Comment by nguyenkims** [comment]
@nkaplatt Hi how did you upgrade to 2.1.2? To upgrade to 2.1.2, please run the same steps to upgrade to the latest version but replace 3.0.1 by 2.1.2, which is the following script

```bash
# Pull the latest version
sudo docker pull simplelogin/app:2.1.2

# Stop SimpleLogin containers
sudo docker stop sl-email sl-migration sl-app

# Make sure to remove these containers to avoid conflict
sudo docker rm -f sl-email sl-migration sl-app

# Run the database migration
sudo docker run --rm \
    --name sl-migration \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -v $(pwd)/simplelogin.env:/code/.env \
    --network="sl-network" \
    simplelogin/app:2.1.2 flask db upgrade

# Run init data
sudo docker run --rm \
    --name sl-init \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/simplelogin.env:/code/.env \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    --network="sl-network" \
    simplelogin/app:2.1.2 python init_app.py

# Run the webapp container
sudo docker run -d \
    --name sl-app \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/simplelogin.env:/code/.env \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -p 7777:7777 \
    --restart always \
    --network="sl-network" \
    simplelogin/app:2.1.2

# Run the email handler container
sudo docker run -d \
    --name sl-email \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/simplelogin.env:/code/.env \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -p 20381:20381 \
    --restart always \
    --network="sl-network" \
    simplelogin/app:2.1.2 python email_handler.py
```

**Comment by nkaplatt** [comment]
Does the `flask db upgrade` step need to be run every time an upgrade occurs then? I was under the impression that moving from v2.1.0 to v2.1.2 didn't require this?

**Comment by nguyenkims** [comment]
> Does the flask db upgrade step need to be run every time an upgrade occurs then? I was under the impression that moving from v2.1.0 to v2.1.2 didn't require this?

The database upgrade to be run for every upgrade actually. The versioning is a bit misleading here indeed, it should be rather v2.2.0 ...

**Comment by nkaplatt** [comment]
Yep can confirm, definitely user error. Have managed to now upgrade to 2.1.2 and then subsequently 3.0.1 - thanks for your help and patience

**Comment by nguyenkims** [comment]
Glad that it worked, I close the issue then.
