### ISSUE TITLE
[HELP] SMTP session time out.

### ISSUE THREAD

**Issue by mzch** [simple-login/app#156]
I tried to send a test mail to self-hosted SimpleLogin, but `python email_handler.py` report an error as below:

```log
May  3 17:59:49 exch mail.sh[3138]: 2020-05-04 00:59:49,460 - sl - DEBUG - 3138 - email_handler:860 - handle_DATA - ===>> New message, mail from mzch@mac.com, rctp tos ['4d8a978e-636b-448c-ad18-0ceee6b81dc9@exch.email']
May  3 18:00:21 exch mail.sh[3138]: SMTP session exception
May  3 18:00:21 exch mail.sh[3138]: Traceback (most recent call last):
May  3 18:00:21 exch mail.sh[3138]:   File "/srv/sl/.pyenv/versions/3.7.7/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 315, in _handle_client
May  3 18:00:21 exch mail.sh[3138]:     await method(arg)
May  3 18:00:21 exch mail.sh[3138]:   File "/srv/sl/.pyenv/versions/3.7.7/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 690, in smtp_DATA
May  3 18:00:21 exch mail.sh[3138]:     status = await self._call_handler_hook('DATA')
May  3 18:00:21 exch mail.sh[3138]:   File "/srv/sl/.pyenv/versions/3.7.7/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 122, in _call_handler_hook
May  3 18:00:21 exch mail.sh[3138]:     status = await hook(self, self.session, self.envelope, *args)
May  3 18:00:21 exch mail.sh[3138]:   File "email_handler.py", line 867, in handle_DATA
May  3 18:00:21 exch mail.sh[3138]:     smtp = SMTP(POSTFIX_SERVER, 25)
May  3 18:00:21 exch mail.sh[3138]:   File "/srv/sl/.pyenv/versions/3.7.7/lib/python3.7/smtplib.py", line 251, in __init__
May  3 18:00:21 exch mail.sh[3138]:     (code, msg) = self.connect(host, port)
May  3 18:00:21 exch mail.sh[3138]:   File "/srv/sl/.pyenv/versions/3.7.7/lib/python3.7/smtplib.py", line 336, in connect
May  3 18:00:21 exch mail.sh[3138]:     self.sock = self._get_socket(host, port, self.timeout)
May  3 18:00:21 exch mail.sh[3138]:   File "/srv/sl/.pyenv/versions/3.7.7/lib/python3.7/smtplib.py", line 307, in _get_socket
May  3 18:00:21 exch mail.sh[3138]:     self.source_address)
May  3 18:00:21 exch mail.sh[3138]:   File "/srv/sl/.pyenv/versions/3.7.7/lib/python3.7/socket.py", line 728, in create_connection
May  3 18:00:21 exch mail.sh[3138]:     raise err
May  3 18:00:21 exch mail.sh[3138]:   File "/srv/sl/.pyenv/versions/3.7.7/lib/python3.7/socket.py", line 716, in create_connection
May  3 18:00:21 exch mail.sh[3138]:     sock.connect(sa)
May  3 18:00:21 exch mail.sh[3138]: TimeoutError: [Errno 110] Connection timed out
```

Anyone can tell me what's wrong?

**Comment by mzch** [comment]
Sorry, it's my mistake. Thanks.

**Comment by cradcore** [comment]
What did you do to fix this? I'm running into the same thing
