### ISSUE TITLE
arm64 docker image no longer available

### ISSUE THREAD

**Issue by KennethWussmann** [simple-login/app#1566]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
The docker image [`simplelogin/app`](https://hub.docker.com/r/simplelogin/app) published to docker hub used to support the `arm64` arch. For example this one month old image [simplelogin/app@4.6.5-beta](https://hub.docker.com/layers/simplelogin/app/4.6.5-beta/images/sha256-d7c6df01d1cde420fb49fbc5b66bbeef8102c6f4af57de767a2047702c6ffae6?context=explore)

The successor [`simplelogin/app-ci`](https://hub.docker.com/r/simplelogin/app-ci) is not multi-arch and only supports `amd64`.

**Expected behavior**
Because `simplelogin/app` does not appear to be updated anymore, I would expect that the successor [`simplelogin/app-ci`](https://hub.docker.com/r/simplelogin/app-ci) supports `arm64` arch just like the previous image did.

**Additional context**
A multi-arch build is missing here: https://github.com/simple-login/app/blob/master/.github/workflows/main.yml#L151-L156

Thank you

**Comment by KennethWussmann** [comment]
@nguyenkims I see. I just hoped that maybe I could use it for testing my [API client](https://github.com/KennethWussmann/simplelogin-client), but understandable if this is currently not a priority.
Thanks for checking.

**Comment by Slevin90** [comment]
For my self-hosted SimpleLogin instance I use a raspberrypi.  `4.6.4-beta` is running good for last few months.
I'd also like to see updates for arm64, helping the self-hosted people

**Comment by Slevin90** [comment]
Additional info: 

@nguyenkims already had arm builds working before:
https://github.com/simple-login/app/issues/270

Seems like new versions haven't been made for https://hub.docker.com/r/simplelogin/app/ ( most recent is 4.6.5-beta)
and it isn't enabled for https://hub.docker.com/r/simplelogin/app-ci/  (on v.4.28.2)

**Comment by Metabaron1** [comment]
Hi
Indeed I'm running on arm64. So I built and pushed 4.22.5 just to try out, but I'm using 4.6.5-beta as is recommended version for self hosting. 
I didn't noticed bug with beta version, and as I only have basic uses and don't really need app-ci new features  ;)

**Comment by Slevin90** [comment]
I'm not looking for features, but having an up to date setup is also a security item to keep in mind.

**Comment by Metabaron1** [comment]
I do not rely on app security, I monitor all network connections.
But indeed, security is a good reason to use app-ci if you only rely on application.
Are you unable to build your own arm62 image on your raspberrypi?

**Comment by Slevin90** [comment]
>Are you unable to build your own arm62 image on your raspberrypi?

I don't know how to build. Prefer it's build by the owner, this could be one thustworthy channel for all arm64 users

**Comment by Metabaron1** [comment]
Best thustworthy channel is your own built one ;)
Here is how to built 4.28.2:

```
wget https://github.com/simple-login/app/archive/refs/tags/v4.28.2.zip
unzip v4.28.2.zip
docker build --tag app:4.28.2 app-4.28.2
```

...
should end up with "Successfully tagged app:4.28.2"

`docker image ls app:4.28.2`
should list : "app          4.28.2    79a493083f9a   About a minute ago   1.58GB"

Now when referencing sl-image in docker command or docker-compose file, just replace official image "simplelogin/app:x.x.x" with your own built image "app:4.28.2"

enjoy!

**Comment by Slevin90** [comment]
building worked (odroid-m1)

updated old database, like the update instructions  ( Note:   `alembic upgrade head`   ins tead of `flask db upgrade`)    : https://github.com/simple-login/app/issues/916#issuecomment-1536045961

had to some problems with critical crash, manually increased the timeout from the sl-app-container from 15 to 45 
gunicorn wsgi:app -b 0.0.0.0:7777 -w 2 --timeout 45


testing-environment works so far.

**Comment by martadams89** [comment]
Should be resolved with https://github.com/simple-login/app/pull/2056

**Comment by ctrl-i** [comment]
They seem to have stopped again.  The latest published version on docker hub seems to be [v4.53.0](https://hub.docker.com/layers/simplelogin/app-ci/v4.53.0/images/sha256-17413b51f2c9c04eaac2404dd7048c1cd7082c62e390d4ae569a614cd587881f?context=explore)

**Comment by martadams89** [comment]
I forked it and added amd64 back into the workflow and made a build here - https://hub.docker.com/layers/martadams89/sl-app/master/images/sha256-a02ed25e8f9c8f7c2d2cf8f538be64dff1b19cf938bab70f7011de7fa39ca511?context=repo

Unfortunately it fails with this error

```
Digest: sha256:d7da583d90861a8b3fc654807e7060729c865ba6934fc44502b3a537884aeb4c
Status: Downloaded newer image for martadams89/sl-app:master
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url_list' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'delim' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'url' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url_list' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'delim' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'url' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'angle_addr' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'name_addr' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'phrase' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url_list' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'delim' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'addr_spec' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'angle_addr' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'name_addr' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'phrase' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'local_part' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'domain' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'quoted_string' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'domain_literal' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'quoted_string_text' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'domain_literal_text' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'mailbox_or_url_list' is unreachable
WARNI [flanker.addresslib._parser.parser] Symbol 'delim' is unreachable
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 552, in run_cmd
    fn(
  File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.10/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/migrations/env.py", line 26, in <module>
    from app.models import Base
  File "/code/app/models.py", line 31, in <module>
    from app import config, rate_limiter
  File "/code/app/config.py", line 79, in <module>
    URL = os.environ["URL"]
  File "/usr/local/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'URL'
```

I don't really know how to fix that, or why it's failing so if someone wants to have a try feel free to make a pull request against my repo here - https://github.com/martadams89/sl-app/

**Comment by martadams89** [comment]
I've set up my workflow to auto merge changes from the main repo to my fork, and a workflow to run weekly to dump an arm image. 

@ctrl-i - this should hopefully keep you going until official arm builds are back
