### ISSUE TITLE
API Method

### ISSUE THREAD

**Issue by SibrenVasse** [simple-login/app#172]
Sending a wrong method to an API endpoint results in a HTTP 500 with html content. (ex: GET to POST or POST to GET)

```
Traceback (most recent call last):
  File "/home/sibren/Proj/app/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sibren/Proj/app/venv/lib/python3.7/site-packages/flask/app.py", line 1810, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/sibren/Proj/app/venv/lib/python3.7/site-packages/flask/app.py", line 1793, in raise_routing_exception
    raise request.routing_exception
  File "/home/sibren/Proj/app/venv/lib/python3.7/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/sibren/Proj/app/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1785, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
```

**Comment by nguyenkims** [comment]
@SibrenVasse do you know how to reproduce this error?

**Comment by SibrenVasse** [comment]
Two examples:

Just send a GET to https://api.simplelogin.io/api/auth/login
```
curl https://api.simplelogin.io/api/auth/login
```

Or a POST to https://api.simplelogin.io/api/user_info
```
curl --request POST https://app.simplelogin.io/api/user_info
```

**Comment by nguyenkims** [comment]
When I tried these `curl` requests, the API returns a HTML error page.

**Comment by SibrenVasse** [comment]
Yeah but a HTML error page is not really appropriate for an API.
Also, HTTP 500 is an internal server error. As the method is wrong, HTTP 405 would be more appropriate. 500 is for notifying the client something is wrong at the server side, but that's not the case. The method is just not supported.

**Comment by nguyenkims** [comment]
@SibrenVasse makes sense indeed. I just created the PR https://github.com/simple-login/app/pull/183 for addressing this.

**Comment by nguyenkims** [comment]
The https://github.com/simple-login/app/pull/183 is now deployed, I close this issue then.
