### ISSUE TITLE
Recommended version to install?

### ISSUE THREAD

**Issue by thecosmicfrog** [simple-login/app#1730]
Hi folks. What is the recommended version of SimpleLogin to install for self-hosted? It's a bit confusing at the moment as the latest images are either `simplelogin/app:4.6.5-beta` or `simplelogin/app-ci:4.28.0` depending on where you look on Docker Hub.

Also, the current documentation on the `master` branch refers to the latest version being `3.4.0`:

https://github.com/simple-login/app/blob/master/docs/upgrade.md#upgrade-to-the-latest-version-340

Thanks!

**Comment by thecosmicfrog** [comment]
@nguyenkims Could you possibly comment on this? Thanks.

**Comment by nguyenkims** [comment]
Hi the `simplelogin/app-ci` is the SaaS version run on app.simplelogin.io, it contains new features but hasn't been tested for self hosting.
The next self hosting version is on the branch `new-self-host-version` and its current docker version is `simplelogin/app:4.6.5-beta`. We recommend using this version as it contains a more up to date code and it is quite stable. We're going to merge it back to the main branch soon and update our README.

**Comment by thecosmicfrog** [comment]
Thanks @nguyenkims. Do you have a rough ETA on when the merge to the main branch will happen? Thanks.

**Comment by caheredia** [comment]
I tried to upgrading from `3.4.0` to `4.6.5-beta` and encountered the error below. I followed these [upgrade instructions](https://github.com/simple-login/app/blob/master/docs/upgrade.md). Are there updated upgrade instructions or did I make a mistake somewhere? 
```python
localhost:~$ docker-compose exec sl-app flask db upgrade
>>> URL: https://app.simplelogin.dedyn.io
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
Paddle param not set
Upload files to local dir
>>> init logging <<<
2023-07-23 18:24:31,590 - SL - DEBUG - 29 - "/code/app/utils.py:14" - <module>() -  - load words file: /code/local_data/words.txt
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 269, in upgrade
    config = current_app.extensions['migrate'].migrate.get_config(directory,
KeyError: 'migrate'
```

**Comment by springcomp** [comment]
Is it possible to upgrade from `4.6.2-beta` to `4.6.5-beta` using migrations or should we always upgrade from the previous stable version ?

**Comment by magn2o** [comment]
To piggyback on @caheredia comment above, for anyone else finding their way here -- the key to a successful upgrade from 3.4.0 to 4.6.x is two-fold:

1. The addition of the `alembic upgrade head` command, which replaces the previous `flask db upgrade`.
2. The addition of a new service command, `python job_runner.py`.

Also, for those using the iOS app as well -- SimpleLogin **2.0.1** (iOS) is the most recent version compatible with **4.6.5-beta.** **_All versions beyond that will toss an error when trying to access the 'My account' tab within the app_**.

**Comment by muhlba91** [comment]
@nguyenkims any information on when 4.6.x will become stable?

**Comment by nguyenkims** [comment]
@muhlba91 This version is actually quite stable, it's just we haven't had the time to test it in a selfhosting mode yet.

**Comment by MuhammadNaeem42** [comment]
i will help you to setup this application 
contact me https://www.fiverr.com/s/9W3PNA
![simple](https://github.com/simple-login/app/assets/106573678/c202c919-f57a-4a7b-9ec4-a7f8fd2a0a01)

**Comment by subhamagr** [comment]
@nguyenkims Hey. Is there an update on this? I hate to see that the latest version of simple login hasn't yet been tested for self-hosted instances. I am currently at 3.4.0 since June of 2021, and would really like to upgrade to the latest version.  

Also, the link https://github.com/simple-login/app/blob/4.6.2-beta/docs/upgrade.md seems to be broken. Is there an updated guide to upgrade from 3.4.0 to the latest version?

Also, I am willing to help you test the latest version for self-hosting. Please help me the major changes to installation methods, services (cron, migration, webapp, admin, etc) and I can set it up to test them and help to prepare an updated installation guide for the community. Please let me know if you'd be interested.

**Comment by muhlba91** [comment]
i'm running 4.38.0 in my kubernetes cluster without any issues. i started off with 4.x already and didn't need to migrate though...

you can find my kubernetes config using fluxcd and kustomize here: https://github.com/muhlba91/muehlbachler-public-services-cluster-applications/tree/main/applications/simplelogin

**Comment by subhamagr** [comment]
So, you are using `app-ci` instead of the `app` docker image? Hows this working for you? Also, did you initially start with installation guide of 3.4.0 (master) and then updated them using the instructions under the [new-self-host-version](https://github.com/simple-login/app/blob/new-self-host-version/docs/upgrade.md) branch?

**Comment by muhlba91** [comment]
i started directly with `app-ci` and 4.x.
i just wanted to avoid a migration and went straight to trying out the 4.x version.
after all, it was a new setup and in the worst case i could simply delete everything and install it using 3.x.

tbh, the `app-ci` version runs smoothly for me and without any problems at all so far. from the initial installation to all updates so far, there was never an issue. i usually wait a few days though to perform a new update just in case...

in the end, i took the instructions from `main` and mixed it with https://github.com/simple-login/app/issues/1803 because i need to support multiple domains.

you can find my postfix related config here: https://github.com/muhlba91/muehlbachler-public-services-infrastructure/tree/main/assets/edge/postfix

**Comment by subhamagr** [comment]
@muhlba91 thanks. I am going to take a full system backup and try to upgrade to v4.6.5-beta. If everything works smoothly, I am going to flip to using `app-ci` images. I will keep you posted.

**Comment by subhamagr** [comment]
okay, I was able to successfully upgrade to v4.6.5-beta docker image tag, and everything seems to be working as expected. I will wait for a week or two and see if I face any issues and after that will upgrade to `app-ci` image tag

**Comment by thecosmicfrog** [comment]
Hi @nguyenkims. Has there been any progress on making version 4 more "official" for self-hosting? Thanks.

**Comment by springcomp** [comment]
@thecosmicfrog @Autopilot9369  for what it’s worth, version `4.6.5-beta` works well in a self-hosted scenario.
You can find the [migrations steps here](https://github.com/springcomp/self-hosted-simplelogin/tree/4.6.x-beta?tab=readme-ov-file#how-to-upgrade) (taken from various responses to discussions from this repository)

I have also been running `4.36.6` without any issues for many months as well. However. So if you feel adventurous, you can find the [migrations steps there](https://github.com/springcomp/self-hosted-simplelogin/tree/4.36.6?tab=readme-ov-file#how-to-upgrade) as well.

**Comment by timespacedecay** [comment]
> @thecosmicfrog @Autopilot9369  for what it’s worth, version `4.6.5-beta` works well in a self-hosted scenario.
> 
> You can find the [migrations steps here](https://github.com/springcomp/self-hosted-simplelogin/tree/4.6.x-beta?tab=readme-ov-file#how-to-upgrade-from-340) (taken from various responses to discussions from this repository)
> 
> 
> 
> I have also been running `4.36.6` without any issues for many months as well. However. So if you feel adventurous, you can find the [migrations steps there](https://github.com/springcomp/self-hosted-simplelogin/tree/4.36.6?tab=readme-ov-file#how-to-upgrade-from-340) as well.

Does 4.36.6 work with the latest version of the iOS app?

**Comment by muhlba91** [comment]
i'm running on `simplelogin/app-ci:v4.69.2` and no issues with the iOS app. since this is a newer version, i would guess yours should work as well.

**Comment by timespacedecay** [comment]
For anyone coming across this in the future, I was able to get on the latest app-ci version (v4.70.0) by doing the following:

1. Upgrade the selfhosted version from 3.4.0 to 4.6.5-beta using the [upgrade guide here](https://github.com/simple-login/app/blob/new-self-host-version/docs/upgrade.md).
2. Upgrade from the selfhosted 4.6.5-beta to app-ci v4.70.0 by following the same guide (sans the items in "After upgrade to 4.x.x from 3.4.0") and replacing `simplelogin/app:4.6.5-beta` with `simplelogin/app-ci:v4.70.0` in each `docker run` where applicable.
3. At this point, the web UI was not accessible and running `docker logs sl-app` indicated a WORKER TIMEOUT error.  I stopped all containers, removed all containers (like in the guide), then re-ran the docker run commands in order.  When I got to the `sl-app` docker run command, after `simplelogin/app-ci:v4.70.0` I added this line to increase the timeout (it basically overrides the [Dockerfile CMD](https://github.com/simple-login/app/blob/9d2a35b9c2e9d23436ba9ca5f50d009c08f226ae/Dockerfile#L47) with the same command but a longer timeout): `gunicorn wsgi:app -b 0.0.0.0:7777 -w 2 --timeout 60` (no quotes) and then continued to bring up the rest of the docker containers listed in the guide, in order.

At that point the stack was up and the web UI was accessible.  The latest version of the SimpleLogin iOS app is fully functional with app-ci:v4.70.0 - no more endpoint errors or errors of any kind when using the iOS app.

My guess is the issue in item 3 above and the need for the longer timeout is because my VPS is rather underpowered, being just 1 core and 1GB.

**Comment by mrehanabbasi** [comment]
> .

I did the exact same thing and can confirm that it works.

**Comment by springcomp** [comment]
@timespacedecay can you please clarify,

After upgrading to 4.6.5-beta, do you just run the 4.70.0 with no problems.
Or are there some additionnal upgrade steps ?

**Comment by timespacedecay** [comment]
> [@timespacedecay](https://github.com/timespacedecay) can you please clarify,
> 
> After upgrading to 4.6.5-beta, do you just run the 4.70.0 with no problems. Or are there some additionnal upgrade steps ?

Correct, no problems other than the WORKER TIMEOUT issue which is probably due to underpowered VPS.

In [your guide here](https://github.com/springcomp/self-hosted-simplelogin/tree/4.36.6?tab=readme-ov-file#how-to-upgrade-from-340), you say to upgrade from 4.6.5-beta to app-ci:v4.36.6 by simply changing the image.  I did that, but went from 4.6.5-beta to to app-ci:v4.70.0.  I ran `sl-migration ` and `sl-init` docker containers as described in the 3.4.0 to 4.6.5 upgrade just in case as well when I was bringing up the app-ci:v4.70.0 stack.  

Again, I did have a WORKER TIMEOUT error on sl-app which caused the Web UI not to load, but simply increasing the timeout time solved that issue and its been working as expected since.

**Comment by springcomp** [comment]
Thanks @timespacedecay,

I have created [a new update to my instructions](https://github.com/springcomp/self-hosted-simplelogin/pull/19) for upgrading to `4.70.0`. Would you be so kind as to confirm this is inline with your steps ?

I was already running version `app-ci:4.36.6` and jumped straight to `app-ci:4.70.0`.
This potentially ran updated `sl-migrations` as well.

So far, this seems to work.

**Comment by thecosmicfrog** [comment]
@nguyenkims @acasajus It's been 2.5 years since I opened this issue, and the latest version of SimpleLogin for self-hosting is officially still `3.4.0`. Is there any future for self-hosting SimpleLogin at this point? It would be better for us to know, so that we can plan for any migrations away to another tool. An update would be greatly appreciated. Thanks 🙂

**Comment by nguyenkims** [comment]
@thecosmicfrog hi the changes between latest version and 3.4.0 is quite minor and that's why we haven't updated it.
