### ISSUE TITLE
Unable to send Verification email - Self Hosted

### ISSUE THREAD

**Issue by mrehanabbasi** [simple-login/app#1956]
I have followed all the instructions for self-hosted and even used the `simplelogin/app:4.5.6-beta` image along with using the `traditional` flag for DKIM keys. However, why registering my first account, I get this error:

`Invalid email, are you sure the email is correct?`

Upon checking the DB, I see that a new user has been added to the `users` table. However, upon checking the logs of `sl-app`, I see that the verification email is not being sent:

```
2023-12-03 22:12:24,761 - SL - DEBUG - 7 - "/code/app/email_utils.py:298" - send_email() -  - send email to myemail@yahoo.com, subject 'Just one more step to join SimpleLogin'
2023-12-03 22:12:24,841 - SL - ERROR - 7 - "/code/app/mail_sender.py:166" - _send_to_smtp() -  - Could not send message to smtp server 10.0.0.1:25
Traceback (most recent call last):
  File "/code/app/mail_sender.py", line 123, in _send_to_smtp
    with SMTP(config.POSTFIX_SERVER, smtp_port) as smtp:
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

I also have enabled `ufw` to allow ports `22`, `25`, `80` and `443`.

Is there anything I am doing wrong or are the instructions not complete/correct?

**Comment by mrehanabbasi** [comment]
I'm not able to connect to host from within the container:

```sh
root@705a1b7af81c:/code# telnet 10.0.0.1 25
Trying 10.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by springcomp** [comment]
Can you share the output of `sudo ufw status` ?

I would suggest disabling the firewall for troubleshooting.
Just out of curiosity, can you please confirm that your host IP is *not* in `10.0.0.x` network ?

**Comment by mrehanabbasi** [comment]
I did turn off the firewall to see if that was causing some issue but that was not the case.

Also, two of my host's interfaces are in the range `10.15.0.x` and `10.104.0.x` respectively. However, even changing the IP range in the docker network to `192.168.0.x` did not work.

**Comment by mrehanabbasi** [comment]
Also, now when I try to create an account or resend the verification email, I get "502 Bad gateway" error from nginx and this in the logs:

```sh
2023-12-05 02:13:54,643 - SL - DEBUG - 337 - "/code/app/email_utils.py:298" - send_email() -  - send email to myemail@yahoo.com, subject 'Just one more step to join SimpleLogin'
[2023-12-05 02:14:10 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:337)
[2023-12-05 02:14:10 +0000] [337] [INFO] Worker exiting (pid: 337)
[2023-12-05 02:14:11 +0000] [343] [INFO] Booting worker with pid: 343
```

**Comment by edleeman17** [comment]
I'm also getting the same as @mrehanabbasi. Same errors, same issue. I got around the account registration by modifying the users table like so...

`UPDATE users SET activated = 't' where email = 'your@email.com';`

But I'm not able to send an email to my alias and have it forwarded as I'm getting connection refused

```
2024-01-13 00:53:38,854 - SL - ERROR - "email_handler.py:1625" - handle_DATA() - 2c99d4b9-0cec-4888-b178-d96d9aadb8f7 - email handling fail test@email-1.com -> ['simplelogin-newsletter.readjusts@mydomain.xyz']
Traceback (most recent call last):
  File "email_handler.py", line 1619, in handle_DATA
    ret = self._handle(envelope)
  File "email_handler.py", line 1643, in _handle
    ret = handle(envelope)
  File "email_handler.py", line 1604, in handle
    for is_delivered, smtp_status in handle_forward(envelope, msg, rcpt_to):
  File "email_handler.py", line 540, in handle_forward
    user,
  File "email_handler.py", line 736, in forward_email_to_mailbox
    is_forward=True,
  File "/code/app/email_utils.py", line 1132, in sl_sendmail
    smtp = SMTP(POSTFIX_SERVER, POSTFIX_PORT_FORWARD)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

- Running on Raspberry Pi 4
- simplelogin/app          3.4.0
- postgres                 12.1

**Comment by mrehanabbasi** [comment]
@edleeman17 I wasn't able to get simplelogin to run. However using [this](https://github.com/springcomp/self-hosted-simplelogin) helped me get it up and running. I'd highly recommend it.

**Comment by edleeman17** [comment]
Thank you! I'll take a look

**Comment by SwapnilSoni1999** [comment]
did you solve the issue?

**Comment by ll3N1GmAll** [comment]
I am having very similar issues. I too can get telnet to work; but when I run the ``docker inspect network sl_network`` command I get:
``[]
Error: No such object: network
Error: No such object: sl_network``

My network name is ``sl_network``. 

I tried to use ``swaks`` to test postfix's ability to send emails; but it fails. I tried to register 2 different email addresses on different service providers; but both failed when attempted via swaks. It looks like it is trying to connect to the imap servers over port 25; but neither provider uses port 25 for imap. One uses 993, so I entered ``swaks --to email@provider.com:993`` and it connected to the server; but failed. 
This was the output:
``=== Trying provider.com:993:25...
=== Connected to provider.com:993.
<** Timeout (30 secs) waiting for server response
 -> QUIT
*** Remote host closed connection unexpectedly.``

**Comment by svpi11** [comment]
I have myself too the same issue. Any idea ? Everything is ok, but not able to send the email for verification and first subscription. (running forever and then 502 bad gateway).

**Comment by svpi11** [comment]
I come back here for same reason, still stuck here... Is this project still maintained ? I've followed exactly the instructions of github

**Comment by ll3N1GmAll** [comment]
My situation has not changed. Still stuck in this same place. Very disheartening. Was very excited about this project; but I cannot move forward due to this issue. Not sure what/if there is a solution.

**Comment by springcomp** [comment]
@svpi11  @ll3N1GmAll 

I understand the frustration.
Allow me to shamelessly plug my [self-hosted setup for SimpleLogin](https://github.com/springcomp/self-hosted-simplelogin) using docker containers.

This works out of the box and will most likely allow you to workaround your issues.
I‘m happy to try and assist if you have specific questions.
