### ISSUE TITLE
Send mail from chrome extension asking to pay on self-hosted

### ISSUE THREAD

**Issue by lunyx** [simple-login/app#2131]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
When clicking the send email button from an alias in the chrome extension, it gives the following error:

> Sending a new email using an alias is a premium feature.

This does NOT occur when opening the dashboard and clicking send email.  The user has `lifetime` and `paid_lifetime` = `True`

**Expected behavior**
The behavior in the chrome extension should be the same or similar as when using the same feature in the dashboard.

**Screenshots**

From dashboard:
![Screenshot 2024-06-19 214509](https://github.com/simple-login/app/assets/6314876/d6eebb82-3d42-422e-ba5f-a23e2770891d)

Premium enabled:
![Screenshot 2024-06-19 214422](https://github.com/simple-login/app/assets/6314876/c45f5998-3f38-4382-81cf-6d3ab29621e4)

From extension:
![Screenshot 2024-06-19 214338](https://github.com/simple-login/app/assets/6314876/28b2faa3-48aa-4862-8b5a-d814111854ae)

**Environment (If applicable):**
 - OS: Windows
 - Browser: Chrome
 - Version 2.11.0

**Comment by lunyx** [comment]
Just tested android app and it works fine there as well.

**Comment by nguyenkims** [comment]
Hi I just tested with a lifetime account for the Chrome extension and don't have this error. I'd suggest to update to v4.44.0 for the self hosting server which is the latest version.

**Comment by lunyx** [comment]
Is there any up to date documentation at all around this?  I noticed the readme is for v3.4.0, which I'm guessing is quite old.  The db migration command doesn't work on the latest version.  Is the latest supposed to be pulled from `simplelogin/app-ci` instead of `simplelogin/app`?  The latter hasn't been updated in over 2 years.

```sudo docker run --rm \
    --name sl-migration \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/sl/upload:/code/static/upload \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -v $(pwd)/simplelogin.env:/code/.env \
    --network="sl-network" \
    simplelogin/app-ci:v4.48.0 flask db upgrade```

```MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
Paddle param not set
Upload files to local dir
>>> init logging <<<
Symbol 'mailbox_or_url_list' is unreachable
Symbol 'delim' is unreachable
Symbol 'mailbox_or_url' is unreachable
Symbol 'url' is unreachable
Symbol 'mailbox_or_url_list' is unreachable
Symbol 'delim' is unreachable
Symbol 'mailbox_or_url' is unreachable
Symbol 'mailbox' is unreachable
Symbol 'url' is unreachable
Symbol 'angle_addr' is unreachable
Symbol 'name_addr' is unreachable
Symbol 'phrase' is unreachable
Symbol 'mailbox_or_url_list' is unreachable
Symbol 'delim' is unreachable
Symbol 'mailbox_or_url' is unreachable
Symbol 'mailbox' is unreachable
Symbol 'addr_spec' is unreachable
Symbol 'angle_addr' is unreachable
Symbol 'name_addr' is unreachable
Symbol 'phrase' is unreachable
Symbol 'local_part' is unreachable
Symbol 'domain' is unreachable
Symbol 'quoted_string' is unreachable
Symbol 'domain_literal' is unreachable
Symbol 'quoted_string_text' is unreachable
Symbol 'domain_literal_text' is unreachable
Symbol 'mailbox_or_url_list' is unreachable
Symbol 'delim' is unreachable
2024-08-05 18:16:22,089 - SL - DEBUG - 1 - "/code/app/utils.py:17" - <module>() -  - load words file: /code/local_data/words.txt
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 269, in upgrade
    config = current_app.extensions['migrate'].migrate.get_config(directory,
KeyError: 'migrate'```

**Comment by lunyx** [comment]
Even with a fresh database, same issue occurs.

**Comment by lunyx** [comment]
Found the documentation.  New version doesn't have the problem.  It would be nice if this was more readily available somewhere than hidden in a branch.  https://github.com/simple-login/app/blob/new-self-host-version/docs/upgrade.md
