### ISSUE TITLE
Exception when email is detected as spam, email lost

### ISSUE THREAD

**Issue by inonio** [simple-login/app#230]
When I receive an email that is marked as spam by spamassassin, I get this error in sl-app docker container (v3.2.2), and the email is lost (instead of showing in the dashboard / quarantine):

```
2020-06-18 22:09:18,251 - sl - WARNING - 1 - email_handler:426 - forward_email_to_mailbox - Email detected as spam. Alias: <Alias 24 my_alias@example.com>, from: <Contact 23 sender_email@example.com 24>
SMTP session exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 315, in _handle_client
    await method(arg)
  File "/usr/local/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 690, in smtp_DATA
    status = await self._call_handler_hook('DATA')
  File "/usr/local/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 122, in _call_handler_hook
    status = await hook(self, self.session, self.envelope, *args)
  File "email_handler.py", line 1111, in handle_DATA
    return handle(envelope, smtp)
  File "email_handler.py", line 1082, in handle
    envelope, smtp, msg, rcpt_to
  File "email_handler.py", line 395, in handle_forward
    alias, copy(msg), email_log, contact, envelope, smtp, mailbox, user
  File "email_handler.py", line 430, in forward_email_to_mailbox
    handle_spam(contact, alias, msg, user, mailbox.email, email_log)
  File "email_handler.py", line 915, in handle_spam
    s3.upload_email_from_bytesio(full_report_path, BytesIO(msg.as_bytes()), random_name)
  File "/code/app/s3.py", line 52, in upload_email_from_bytesio
    _session.resource("s3").Bucket(BUCKET).put_object(
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/factory.py", line 474, in create_resource
    client=self.meta.client)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/base.py", line 119, in __init__
    'Required parameter {0} not set'.format(identifier))
ValueError: Required parameter name not set```

**Comment by inonio** [comment]
I had to set LOCAL_FILE_UPLOAD to TRUE. closing.
