### ISSUE TITLE
Running SimpleLogin alongside other mail client

### ISSUE THREAD

**Issue by dducted** [simple-login/app#239]
Hi there,

Am I able to run SimpleLogin while using the same domain for mailbox.org? Or will that cause a conflict? I will be having several MX, dmarc, etc records. 

Thanks for your help!

**Comment by nguyenkims** [comment]
@dducted Hi you cannot use the same domain on 2 different email services (mailbox and SimpleLogin in this case). You can however use a subdomain on SimpleLogin and keep the root domain on mailbox. Some users use this approach with GSuite and it works well :).

**Comment by dducted** [comment]
Thanks for information and your prompt reply, appreciate that. 

I'd have one more question, after full installation I'm left with the following log entry:
```
greylisting:70 - greylisting_needed_forward_phase - alias XXX@XXX.com not exist. Try to see if it can be created on the fly
email_handler:1080 - handle - >>> Forward phase <> -> XXX@XXX.com
email_handler:372 - handle_forward - alias XXX@XXX.com not exist. Try to see if it can be created on the fly
email_handler:375 - handle_forward - alias XXX@XXX.com cannot be created on-the-fly, return 550
```
This pops up once I created an account - waiting to receive the activation email. A little unsure how I can create the `SUPPORT_EMAIL` email accordingly.

**Comment by dducted** [comment]
I also seem to get the following error:

```
SMTP session exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 315, in _handle_client
    await method(arg)
  File "/usr/local/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 690, in smtp_DATA
    status = await self._call_handler_hook('DATA')
  File "/usr/local/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 122, in _call_handler_hook
    status = await hook(self, self.session, self.envelope, *args)
  File "email_handler.py", line 1111, in handle_DATA
    return handle(envelope, smtp)
  File "email_handler.py", line 1077, in handle
    is_delivered, smtp_status = handle_reply(envelope, smtp, msg, rcpt_to)
  File "email_handler.py", line 550, in handle_reply
    handle_bounce(contact, alias, msg, user)
  File "email_handler.py", line 781, in handle_bounce
    s3.upload_email_from_bytesio(full_report_path, BytesIO(msg.as_bytes()), random_name)
  File "/code/app/s3.py", line 52, in upload_email_from_bytesio
    _session.resource("s3").Bucket(BUCKET).put_object(
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/factory.py", line 474, in create_resource
    client=self.meta.client)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/base.py", line 119, in __init__
    'Required parameter {0} not set'.format(identifier))
ValueError: Required parameter name not set
```
Not quite sure where I have to set the parameter `name`

**Comment by dducted** [comment]
Seems like the first mentioned issues solved itself, somehow -- however the second one persist.

> `ValueError: Required parameter name not set`

**Comment by dducted** [comment]
Open a [new issue](https://github.com/simple-login/app/issues/240) for the previously mentioned error log. Closing this issue.
