### ISSUE TITLE
SMTP session exception

### ISSUE THREAD

**Issue by dducted** [simple-login/app#240]
I am getting the following SMTP exception error. Hope anybody has an idea how I could possibly fix that.

```
SMTP session exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 315, in _handle_client
    await method(arg)
  File "/usr/local/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 690, in smtp_DATA
    status = await self._call_handler_hook('DATA')
  File "/usr/local/lib/python3.7/site-packages/aiosmtpd/smtp.py", line 122, in _call_handler_hook
    status = await hook(self, self.session, self.envelope, *args)
  File "email_handler.py", line 1111, in handle_DATA
    return handle(envelope, smtp)
  File "email_handler.py", line 1077, in handle
    is_delivered, smtp_status = handle_reply(envelope, smtp, msg, rcpt_to)
  File "email_handler.py", line 550, in handle_reply
    handle_bounce(contact, alias, msg, user)
  File "email_handler.py", line 781, in handle_bounce
    s3.upload_email_from_bytesio(full_report_path, BytesIO(msg.as_bytes()), random_name)
  File "/code/app/s3.py", line 52, in upload_email_from_bytesio
    _session.resource("s3").Bucket(BUCKET).put_object(
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/factory.py", line 474, in create_resource
    client=self.meta.client)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/base.py", line 119, in __init__
    'Required parameter {0} not set'.format(identifier))
ValueError: Required parameter name not set
```
Not quite sure where I have to set the parameter `name`

Thanks for your help!

**Comment by nguyenkims** [comment]
@dducted Sorry for the error! Please set `LOCAL_FILE_UPLOAD=1` option in your env file to upload bounced emails to a local directory instead. I also updated the README to add this option by default.

Let me know if the error still persists after setting this option and restarting the containers.

**Comment by dducted** [comment]
Sweet, thanks for the update. I'll close the issue for now. In case the issue persist I'll re-open it.
