### ISSUE TITLE
database migration - paddle key error

### ISSUE THREAD

**Issue by ThatFatRat** [simple-login/app#326]
Hello,
Please excuse me if I am reporting this incorrectly as I am new to Github.

I was following your guide and ran into an error trying to run the docker container. I copied your simplelogin.env file and made the necessary changes. But when I run the database migration I get this error. It looks like the script is looking for the paddle configuration information even though I did not specify it since it was optional.

`[user@host ~]$ sudo docker run --rm     --name sl-migration     -v $(pwd)/sl:/sl     -v $(pwd)/sl/upload:/code/static/upload     -v $(pwd)/dkim.key:/dkim.key     -v $(pwd)/dkim.pub.key:/dkim.pub.key     -v $(pwd)/simplelogin.env:/code/.env     --network="sl-network"     simplelogin/app:3.2.2 flask db upgrade
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 906, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 418, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 386, in load_app
    raise_if_not_found=False)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 236, in locate_app
    __import__(module_name)
  File "/code/wsgi.py", line 1, in <module>
    from server import create_app
  File "/code/server.py", line 15, in <module>
    from app import paddle_utils
  File "/code/app/paddle_utils.py", line 18, in <module>
    from app.config import PADDLE_PUBLIC_KEY_PATH, PADDLE_VENDOR_ID, PADDLE_AUTH_CODE
  File "/code/app/config.py", line 39, in <module>
    URL = os.environ["URL"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'URL'`

This is my simplelogin.env configuration file. I have made no additional changes and the DKIM keys are in my home directory. from which I ran the migration command.
`  GNU nano 5.3                                                                                                   simplelogin.env                                                                                                              
# WebApp URL
URL=http://app.[redacted].com

# domain used to create alias
EMAIL_DOMAIN=[redacted].com

# transactional email is sent from this email address
SUPPORT_EMAIL=support@[redacted].com

# custom domain needs to point to these MX servers
EMAIL_SERVERS_WITH_PRIORITY=[(10, "app.[redacted].com.")]

# By default, new aliases must end with ".{random_word}". This is to avoid a person taking all "nice" aliases.
# this option doesn't make sense in self-hosted. Set this variable to disable this option.
DISABLE_ALIAS_SUFFIX=1

# If you want to use another MTA to send email, you could set the address of your MTA here
# By default, emails are sent using the the same Postfix server that receives emails
# POSTFIX_SERVER=my-postfix.com

# the DKIM private key used to compute DKIM-Signature
DKIM_PRIVATE_KEY_PATH=/dkim.key

# the DKIM public key used to setup custom domain DKIM
DKIM_PUBLIC_KEY_PATH=/dkim.pub.key

# DB Connection
DB_URI=postgresql://[redacted]:[redacted]-D7@sl-db:5432/simplelogin

FLASK_SECRET=[redacted]

GNUPGHOME=/sl/pgp

LOCAL_FILE_UPLOAD=1`

Please let me know any tips to resolve this issue or any additional information you need. I have only been running on linux for a few months now so I still don't have the skill to track down the root cause on these projects.

**Comment by tadinski** [comment]
@ThatFatRat what was the solution?
