### ISSUE TITLE
README "Run code locally" no longer works (AWS required?)

### ISSUE THREAD

**Issue by TheLastProject** [simple-login/app#375]
A few tests in pytest fail, but that I kinda expect because it's running offline and not in a real email environment. But worse than that...

After the `cp example.env .env` step and uncommenting `RESET_DB=true`, the server fails to start with the following error:
```
~/Projects/Forks/SimpleLogin/app-1(master) » python3 server.py
>>> URL: http://localhost:7777
WARNING: Use a temp directory for GNUPGHOME /tmp/rbodgtsvvuboftcnuyvu
>>> init logging <<<                                                                                        
2021-03-05 22:02:12,160 - sl - DEBUG - 510738 - utils:11 - <module> - load words file: /home/sylvia/Projects
/Forks/SimpleLogin/app-1/local_data/words.txt
2021-03-05 22:02:13,626 - sl - WARNING - 510738 - server:838 - local_main - reset db, add fake data
2021-03-05 22:02:13,627 - sl - DEBUG - 510738 - server:194 - fake_data - create fake data
2021-03-05 22:02:13,627 - sl - DEBUG - 510738 - server:197 - fake_data - remove existing db file
2021-03-05 22:02:20,430 - sl - DEBUG - 510738 - models:317 - create - Disable onboarding emails
Traceback (most recent call last):
  File "/home/sylvia/Projects/Forks/SimpleLogin/app-1/server.py", line 854, in <module>
    local_main()
  File "/home/sylvia/Projects/Forks/SimpleLogin/app-1/server.py", line 840, in local_main
    fake_data()
  File "/home/sylvia/Projects/Forks/SimpleLogin/app-1/server.py", line 220, in fake_data
    s3.upload_from_bytesio( 
  File "/home/sylvia/Projects/Forks/SimpleLogin/app-1/app/s3.py", line 36, in upload_from_bytesio
    _session.resource("s3").Bucket(BUCKET).put_object( 
  File "/home/sylvia/.local/lib/python3.9/site-packages/boto3/session.py", line 384, in resource
    client = self.client(
  File "/home/sylvia/.local/lib/python3.9/site-packages/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/home/sylvia/.local/lib/python3.9/site-packages/botocore/session.py", line 797, in create_client
    region_name = self._resolve_region_name(region_name, config)
  File "/home/sylvia/.local/lib/python3.9/site-packages/botocore/session.py", line 853, in _resolve_region_n
ame
    validate_region_name(region_name)
  File "/home/sylvia/.local/lib/python3.9/site-packages/botocore/utils.py", line 1016, in validate_region_na
me
    raise InvalidRegionError(region_name=region_name)
botocore.exceptions.InvalidRegionError: Provided region_name 'to_fill' doesn't match a supported format.
```

This one was pretty logical, it is because the AWS settings aren't commented out: https://github.com/simple-login/app/blob/193f8d8ccc95b5437e61fd57b6447aa7d6898226/example.env#L91-L95

After commenting these out, however, it still fails:
```
~/Projects/Forks/SimpleLogin/app-1(master) » python3 server.py
>>> URL: http://localhost:7777
WARNING: Use a temp directory for GNUPGHOME /tmp/vhlaigfniipvgtslizvb
>>> init logging <<<
2021-03-05 22:02:38,843 - sl - DEBUG - 510867 - utils:11 - <module> - load words file: /home/sylvia/Projects
/Forks/SimpleLogin/app-1/local_data/words.txt
2021-03-05 22:02:39,501 - sl - WARNING - 510867 - server:838 - local_main - reset db, add fake data
2021-03-05 22:02:39,501 - sl - DEBUG - 510867 - server:194 - fake_data - create fake data
2021-03-05 22:02:39,501 - sl - DEBUG - 510867 - server:197 - fake_data - remove existing db file
2021-03-05 22:02:49,534 - sl - DEBUG - 510867 - models:317 - create - Disable onboarding emails
Traceback (most recent call last):
  File "/home/sylvia/Projects/Forks/SimpleLogin/app-1/server.py", line 854, in <module>
    local_main()
  File "/home/sylvia/Projects/Forks/SimpleLogin/app-1/server.py", line 840, in local_main
    fake_data()
  File "/home/sylvia/Projects/Forks/SimpleLogin/app-1/server.py", line 220, in fake_data
    s3.upload_from_bytesio( 
  File "/home/sylvia/Projects/Forks/SimpleLogin/app-1/app/s3.py", line 36, in upload_from_bytesio
    _session.resource("s3").Bucket(BUCKET).put_object( 
  File "/home/sylvia/.local/lib/python3.9/site-packages/boto3/resources/factory.py", line 473, in create_res
ource
    return partial(resource_cls, *positional_args,
  File "/home/sylvia/.local/lib/python3.9/site-packages/boto3/resources/base.py", line 118, in __init__
    raise ValueError(
ValueError: Required parameter name not set
```

It seems AWS is required for the test data now even to develop locally?

**Comment by nguyenkims** [comment]
@TheLastProject hey the `example.env` is indeed not up-to-date. I have updated the repo with the latest change and simplify the local setup, you can can check out the new doc at https://github.com/simple-login/app/blob/master/CONTRIBUTING.md :)

**Comment by nguyenkims** [comment]
AWS isn't needed for local development (the app can run without Internet) and is now commented out by default in `example.env`

**Comment by TheLastProject** [comment]
Thank you, that fixed it (I missed the LOCAL_FILE_UPLOAD option, but it is nice the example .env is now usable for local development)

**Comment by nguyenkims** [comment]
@TheLastProject the `LOCAL_FILE_UPLOAD` is now enabled by default in example.env. It's also the option used by default on a self-hosted instance :).
