### ISSUE TITLE
Error when trying to run from source

### ISSUE THREAD

**Issue by Heziode** [simple-login/app#949]
Please note that this is only for bug report. 

For help on your account, please reach out to us at hi[at]simplelogin.io. Please make sure to check out [our FAQ](https://simplelogin.io/faq/) that contains  frequently asked questions.

For feature request, you can use our [forum](https://github.com/simple-login/app/discussions/categories/feature-request). 

For self-hosted question/issue, please ask in [self-hosted forum](https://github.com/simple-login/app/discussions/categories/self-hosting-question)

## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

**Describe the bug**
When I attempt to run the migration from source (docker image build from source), I got the following error:

```
# docker run --rm \
>     --name sl-migration \
>     -v $(pwd)/sl:/sl \
>     -v $(pwd)/sl/upload:/code/static/upload \
>     -v $(pwd)/dkim.key:/dkim.key \
>     -v $(pwd)/dkim.pub.key:/dkim.pub.key \
>     -v $(pwd)/simplelogin.env:/code/.env \
>     --network="sl-network" \
>     local/simple-login-app:2022-05-03 flask db upgrade
>>> URL: http://sl.mydomain.com
MAX_NB_EMAIL_FREE_PLAN is not set, use 5 as default value
Paddle param not set
Upload files to local dir
>>> init logging <<<
Symbol 'mailbox_or_url_list' is unreachable
Symbol 'delim' is unreachable
Symbol 'mailbox_or_url' is unreachable
Symbol 'url' is unreachable
Symbol 'mailbox_or_url_list' is unreachable
Symbol 'delim' is unreachable
Symbol 'mailbox_or_url' is unreachable
Symbol 'mailbox' is unreachable
Symbol 'url' is unreachable
Symbol 'angle_addr' is unreachable
Symbol 'name_addr' is unreachable
Symbol 'phrase' is unreachable
Symbol 'mailbox_or_url_list' is unreachable
Symbol 'delim' is unreachable
Symbol 'mailbox_or_url' is unreachable
Symbol 'mailbox' is unreachable
Symbol 'addr_spec' is unreachable
Symbol 'angle_addr' is unreachable
Symbol 'name_addr' is unreachable
Symbol 'phrase' is unreachable
Symbol 'local_part' is unreachable
Symbol 'domain' is unreachable
Symbol 'quoted_string' is unreachable
Symbol 'domain_literal' is unreachable
Symbol 'quoted_string_text' is unreachable
Symbol 'domain_literal_text' is unreachable
Symbol 'mailbox_or_url_list' is unreachable
Symbol 'delim' is unreachable
2022-05-04 12:49:28,022 - SL - DEBUG - 1 - "/code/app/utils.py:14" - <module>() -  - load words file: /code/local_data/words.txt
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 14, in <module>
    fileConfig(config.config_file_name)
  File "/usr/local/lib/python3.7/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/local/lib/python3.7/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```

**Expected behavior**

The the migration goes smoothly.

**Environment (If applicable):**
 - OS: Linux, Ubuntu (5.4.0-109-generic)
 - Browser: N/C

**Additional context**

Step to reproduce:

```
# Clone the repo
git clone https://github.com/simple-login/app/ simple-login-app
cd simple-login-app

# Checkou to the same commit as https://app.simplelogin.io/git
git checkout 67dad33b700d86c9364092f8efa32fe289fcc5e0

# Build image
docker build -t local/simple-login-app:2022-05-03 .

# Go to the working director of our instance
cd /path/to/your/simple-login/working-dirctory

ls -1
# dkim.key
# dkim.pub.key
# simplelogin.env
# sl

# This is a clean install, without DB
ls -1 sl
# output

# Run the database container. Make sure to replace `myuser` and `mypassword`
docker run -d \
    --name sl-db \
    -e POSTGRES_PASSWORD=mypassword \
    -e POSTGRES_USER=myuser \
    -e POSTGRES_DB=simplelogin \
    -p 127.0.0.1:5432:5432 \
    -v $(pwd)/sl/db:/var/lib/postgresql/data \
    --restart always \
    --network="sl-network" \
    postgres:12.1

docker run --rm \
    --name sl-migration \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/sl/upload:/code/static/upload \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -v $(pwd)/simplelogin.env:/code/.env \
    --network="sl-network" \
    local/simple-login-app:2022-05-03 flask db upgrade

```

**Comment by nguyenkims** [comment]
Do you have the right database credential in the `$(pwd)/simplelogin.env` file?

**Comment by Heziode** [comment]
Inside this file, I have a variable defined like this: `DB_URI=postgresql://myuser:mypassword@sl-db:5432/simplelogin
`

Where I have replaced `myuser` and `mypassword` with the right values.

**Comment by nguyenkims** [comment]
Do you know if the database container is started successfully?

**Comment by Heziode** [comment]
Yep, it is started successfully, I can log into the container using: `docker exec -it sl-db psql -U myuser simplelogin`

**Comment by nguyenkims** [comment]
I think the issue comes from the `flask db upgrade` command, we are now using alembic instead.

Can you try to run this command instead?

```
docker run --rm \
    --name sl-migration \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/sl/upload:/code/static/upload \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -v $(pwd)/simplelogin.env:/code/.env \
    --network="sl-network" \
    local/simple-login-app:2022-05-04-67dad33b700d86c9364092f8efa32fe289fcc5e0 alembic upgrade head
```

**Comment by Heziode** [comment]
@nguyenkims yes it works now.

So, the README is not up to date, since it always show the `flask db upgrade`.
But a question arises: Should I update it now or wait for the next release? Because the instruction with  `alembic upgrade head` will not work with v3.4.0

**Comment by nguyenkims** [comment]
I think it's better to wait for the release of the next version :)

**Comment by akash07k** [comment]
@nguyenkims  Any plans to release the latest builds for selfhosting?

**Comment by nguyenkims** [comment]
@akash07k the next version is https://github.com/simple-login/app/tree/4.6.2-beta which is quite stable now and we plan to release it next week.
